# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.contigCells <- function(pt, dim1, dim2) {
    .Call('landscapeR_contigCells_cpp', PACKAGE = 'landscapeR', pt, dim1, dim2)
}

.indexTranspose <- function(id, dim1, dim2) {
    .Call('landscapeR_indexTranspose_cpp', PACKAGE = 'landscapeR', id, dim1, dim2)
}

